# APPLICATION
server:
  port: ${USERS_PORT:8080}

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://${USERS_DATABASE_URI:localhost:5432}/deliver
    schema: users
    username: postgres
    password: postgres
  flyway:
    schemas: users
  liquibase:
    enabled: false
#    defaultSchema: users
  # JPA
  jpa:
    open-in-view: false

### Keycloak Configuration
keycloak:
  auth-server-url: {USERS_AUTH_HOST:http://localhost:8080}/auth/
  realm: external
  resource: external-client
  public-client: false
  bearer-only: false
  principal-attribute: preferred_username
  credentials.secret: xxxxxxxxx
  use-resource-role-mappings: true
  confidential-port: ${USERS_CONFIDENTIAL_PORT:8090}
  ssl-required: none

