# APPLICATION
server:
  port: ${ORDERS_PORT:8080}

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://${ORDERS_DATABASE_URI:localhost:5432}/deliver
    schema: orders
    username: postgres
    password: postgres
  # MIGRATION
  liquibase:
    default-schema: ${spring.datasource.schema}
  # JPA
  jpa:
    open-in-view: false

# KAFKA PROPERTIES
  kafka:
    bootstrap-servers: ${ORDERS_KAFKA_SERVERS:localhost:9092}
    producer:
      client-id: ${ORDERS_KAFKA_CLIENT_ID:local_developer}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: ${ORDERS_GROUP_ID:local}

# KAFKA TOPICS
topic:
  order:
    order-topic: com.deliver.order-service.v1.order
    courier-management: com.deliver.order-service.v1.courier-management
    order-status-in: com.deliver.tracked-service.v1.order-status

# SWAGGER
#springdoc.swagger-ui.path: /swagger-ui
