# APPLICATION
server:
  port: ${GATEWAY_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        #ORDER ROUTING
        - id: orders
          uri: http://deliver_order:8080/api/v1/
          predicates:
            Path=/api/v1/

        # USERS ROUTING
        - id: users
          uri: http://deliver_users:8080/api/v1/
          predicates:
            Path=/api/v1/

        # KEYCLOAK ROUTING
        - id: keycloak
          uri: http://keycloak:8080/auth
          predicates:
            Path=/auth


  # SECURITY
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak-provider
            client-id: ${USERS_AUTH_CLIENT_ID:users_client_id}
            client-secret: ${USERS_AUTH_CLIENT_SECRET:users_client_secret}
            authorization-grant-type: authorization_code
            redirect-uri: "http://gateway_service:8080/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          keycloak-provider:
            issuer-uri: http://gateway_service:8080/auth/realms/deliver
